# Available languages: eng (English), rus (Русский), ukr (Українська), spa (Español)
language: "eng"

# Update mines if there are no players on the server
# Disabling this option can improve performance
update-if-no-players: true

# Commands
commands:
  mine:
    name: "mine"         # Command name
    description: "Mines" # Command description
    aliases: ["mines"]   # Command aliases
