# Available languages: eng (English), rus (Русский), spa (Español)
language: "eng"

# Update mines if there are no players on the server
# Disabling this option can improve performance
update-if-no-players: true